inherit_from: .rubocop_todo.yml

# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md
## rubocop 関連の gem を require します。
require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

## Exclude チェック対象外
AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.2
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'config/environments/*'
    - 'lib/**/*'

Rails:
  Enabled: true

Rails/FilePath:
  Exclude:
    - 'lib/tasks/dev.rake'
    - 'spec/rails_helper.rb'


## 日本語コメントを許可します。
Style/AsciiComments:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/CommentIndentation:
  Enabled: false

# Hash#has_key? は許可したい
Style/PreferredHashMethods:
  Enabled: false

#hashの書き方、 key: :valueを許容する。
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

#Filepathの書き方。slashsで書く
Rails/FilePath:
  EnforcedStyle: slashes

#rspecはブロックの長さが長くなるので・・・
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# RspecでAmbiguousBlockAssociationは見ないようにする
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

# Rspecで日本語記法で書くと必ずひっかかるため
RSpec/ContextWording:
  Enabled: false

#クラス名を使う
RSpec/DescribedClass:
  EnforcedStyle: explicit

#Rspecの空のグループを許容する
RSpec/EmptyExampleGroup:
    Enabled: false
